### ISSUE TITLE
Possible to publish 3.3.3 due to rollback?

### ISSUE THREAD

**Issue by KevinGrandon** [adriantoine/enzyme-to-json#100]
Just wondering if it's possible to publish 3.3.3. We have some folks with yarn caches that say that 3.3.2 is valid, and it's troublesome to invalidate the cache due to the rollback.

If we publish 3.3.3 (even if the same code), folks should automatically be upgraded.

**Comment by adriantoine** [comment]
Ok I will publish `3.3.3` with no fix or update in it.

**Comment by adriantoine** [comment]
That's done @KevinGrandon, again and again and again, sorry for the inconvenience!

As someone pointed out, I should have published the rollback as a `3.3.3` rather than unpublishing the version, a few bad decisions have been made on this incident, at least I learned from it 😅sorry that it was at the expense of all your builds breaking.

**Comment by robrichard** [comment]
IMO `4.0.0` should have been published instead of `3.3.3` as many projects were already updated to `3.3.2` before it was unpublished. `3.3.3` introduces a second breaking change to the projects already on `3.3.2`.

**Comment by apaatsio** [comment]
@robrichard Yeah, that's a bit unfortunate. But I would suppose most of those projects are aware of this situation and they just won't update to 3.3.3 but wait for 4.0.0 instead.

If for some reason they want to update from 3.3.2 to 3.3.3 it requires just one `git revert` to revert the breaking changes anyway :grin:
