### ISSUE TITLE
Configure serializer to skip element attributes on snapshot.

### ISSUE THREAD

**Issue by dzhytomyrsky** [adriantoine/enzyme-to-json#57]
Hello is it possible to configure serializer to skip element attributes? It would be wonderful to get on snapshot only elements and innerText.

```js
<ul
  className="bottomMasked"
  id="agentsList"
  onScroll={[Function]}
>
  <li
    className={null}
    onClick={[Function]}
>
    Detective Inspector Lee
  </li>
</ul>
```

**Comment by runk** [comment]
Would be awesome to have this feature. 💯

**Comment by JonathanTR** [comment]
What would it look to configure this?

**Comment by adriantoine** [comment]
Hi!

Thanks for your suggestions, would you mind giving more details about that? I don't think I understand, you want a snapshot with only elements and inner texts?

`enzyme-to-json` is only converting Enzyme wrappers to a JSON format that is compatible with Jest snapshot testing. Isn't that something you want to be implemented in Jest so that it is available for people only using `react-test-renderer`?

**Comment by JonathanTR** [comment]
Ah, I'm realizing that what I wanted was actually quite different from OP, as I had read their post pretty quickly. What I was thinking was something more along the lines of being able to collapse certain elements within a snapshot. 

So instead of having:
```javascript
<Button
  color="blue"
>
  <button
    className="button blue"
  >
  </button>
</Button>
```

I could configure my serializer to just return something like:
```javascript
<Button
  color="blue"
>
  { [children] }
</Button>
```

This would be awesome for cleaning up snapshots, especially in cases where there's lots of HOC's wrapped up in an implementation.

**Comment by adriantoine** [comment]
I'm working on a map functionality (see #48) which would give much more control on the output. It will be released with [`v3.0.0`](https://github.com/adriantoine/enzyme-to-json/issues/67).

Thanks for your suggestions!

**Comment by adriantoine** [comment]
@JonathanTR @dzhytomyrsky @runk I just [added a comment](https://github.com/adriantoine/enzyme-to-json/issues/67#issuecomment-330368493) to #67 about this new mapping functionality, can you tell me if it solves your issue?

Thanks!

**Comment by adriantoine** [comment]
`v3.0.0` has been released 🎉, the map functionality should cover this use case, if not, please comment on this issue!
